### ISSUE TITLE
SSH Connection Error

### ISSUE THREAD

**Issue by severindellsperger** [jklaiber/jumper#13]
The code panics as soon as I want to connect to a host.

```
jumper connect -g test test-server
Connecting to 172.16.xx.xx with xxx

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5d8e3c]

goroutine 10 [running]:
golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc00020a800, 0xc000216340)
	/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/ssh/client_auth.go:65 +0x53c
golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc00020a800, {0xc000016a60, 0xf}, 0xc000216340)
	/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/ssh/client.go:113 +0x285
golang.org/x/crypto/ssh.NewClientConn({0x8d6660, 0xc000010030}, {0xc000016a60, 0xf}, 0xc0000b2750)
	/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/ssh/client.go:83 +0x12e
golang.org/x/crypto/ssh.Dial({0x825af3?, 0xc000092cc0?}, {0xc000016a60, 0xf}, 0xc0000b2750)
	/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210921155107-089bfa567519/ssh/client.go:177 +0x59
github.com/jklaiber/jumper/pkg/connection.runShell({0x8d5550?, 0xc0000762c0}, {0xc000092cc0?, 0xc000112200?}, 0x8d5550?)
	/github/workspace/pkg/connection/connection.go:87 +0x92
github.com/jklaiber/jumper/pkg/connection.NewConnection.func1()
	/github/workspace/pkg/connection/connection.go:71 +0x36
created by github.com/jklaiber/jumper/pkg/connection.NewConnection
	/github/workspace/pkg/connection/connection.go:70 +0x54d
```

There can be many reasons for this problem. I will dig into what causes it.

**Comment by severindellsperger** [comment]
The problem is related to SSH keys, which are protected by a passphrase. In the case an encrypted SSH key is used, the parsing of the SSH key fails, which is not covered by the code. Thus the execution panics because of a nil pointer.
I will create a PR to fix the problem. Code changes can be found here: https://github.com/jklaiber/jumper/tree/fix-ssh-connection-error
